### ISSUE TITLE
Not full response saved

### ISSUE THREAD

**Issue by romrayster** [Michelangelo27/chatgpt_selenium_automation#9]
Hello,
Again great work on the tool - for me it breaks off afters saving maybe half the response? It doesn't wait until chatgpt generated the response until  the end.

Something I can do about it?

**Comment by Michelangelo27** [comment]
Hi, 
thanks :)
in the function "send_prompt_to_chatgpt" is defined a time.sleep which says for how long the script will wait for chatgpt response u can increase the number. A better solution would be a command that automatically checks if chatgpt has already finished responding.
